# Generated by Django 5.2 on 2025-04-09 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="last_activity",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="login_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="watchlist",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="StockInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=10)),
                ("view_count", models.IntegerField(default=0)),
                ("last_viewed", models.DateTimeField(blank=True, null=True)),
                ("search_count", models.IntegerField(default=0)),
                ("last_searched", models.DateTimeField(blank=True, null=True)),
                ("total_view_time", models.IntegerField(default=0)),
                ("is_favorite", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_interactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "symbol")},
            },
        ),
        migrations.CreateModel(
            name="UserActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("view_stock", "View Stock"),
                            ("view_news", "View News"),
                            ("add_to_watchlist", "Add to Watchlist"),
                            ("remove_from_watchlist", "Remove from Watchlist"),
                            ("search", "Search"),
                            ("create_alert", "Create Alert"),
                            ("view_prediction", "View Prediction"),
                            ("dashboard_interaction", "Dashboard Interaction"),
                            ("settings_changed", "Settings Changed"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("session_id", models.CharField(blank=True, max_length=40)),
                ("object_id", models.CharField(blank=True, max_length=50)),
                ("content_type", models.CharField(blank=True, max_length=50)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "User activities",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "timestamp"],
                        name="accounts_us_user_id_f07708_idx",
                    ),
                    models.Index(
                        fields=["activity_type"], name="accounts_us_activit_8a5b92_idx"
                    ),
                ],
            },
        ),
    ]
